name: abalone
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - catboost
  - xgboost
  - lightgbm
  - matplotlib
  - seaborn
  - joblib
  - optuna
  - scipy
  - pip
  - pip:
      - black
      - isort
      - ruff
      - pytest
      - pytest-cov
      - pre-commit
